const baseUrl = 'http://localhost:3000';
const buttonDiv = () => document.getElementById('button-control');
const buttonShow = () => document.getElementById('button-show');
const buttonNew = () => document.getElementById('button-new');
const ulDiv = () => document.getElementById('list');
const ul = () => document.getElementById('categories-list');
const videoForm = () => document.getElementById('video-form');
const videoUrl = () => document.getElementById('video_url');
const videoCategory = () => document.getElementById('category_id');
const videoIndex = () => document.getElementById('video-index');
const categoriesSection = () => document.querySelector('#categories-section');
const renderShow = () => document.getElementById('render-show');
const catName = () => document.getElementById('name');
const categoryForm = () => document.getElementById('category-form');
